root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "@unocss"
  - "prettier"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "dist"
